version: '3'
services:
    
  perfectify:
    build: ./perfectify
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./perfectify/code:/code
      - ./perfectify/code/static:/code/staticfiles      
