# Generated by Django 2.2.10 on 2021-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_background_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_face_clearly_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_facemask_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_obstacle_exists',
            field=models.BooleanField(default=False),
        ),
    ]
