# Generated by Django 2.2.10 on 2021-08-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210715_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_background_correct',
            new_name='is_background_success',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='is_face_clearly_shown',
            new_name='is_face_clarity_success',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='is_facemask_exists',
            new_name='is_facemask_success',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='is_obstacle_exists',
            new_name='is_obstacle_success',
        ),
    ]
